FROM jenkins/inbound-agent:latest-jdk17  

USER root

# Install Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*  

# Install Python, venv, and pip
RUN apt-get update && \
    apt-get install -y python3 python3-venv python3-pip && \
    rm -rf /var/lib/apt/lists/*     

RUN ln -sf /usr/bin/python3 /usr/bin/python


USER jenkins
